apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: commons-sub
  namespace: kubedatastack-operators
spec:
  channel: stable
  name: commons-operator
  source: commons-catalog
  sourceNamespace: olm
  installPlanApproval: Automated