## Append samples of your project ##
resources:
- authentication_v1alpha1_authenticationclass.yaml
- s3_v1alpha1_s3connection.yaml
- s3_v1alpha1_s3bucket.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
