## Append samples of your project ##
resources:
- v1alpha1_databaseconnection.yaml
- v1alpha1_database.yaml
- v1alpha1_s3bucket.yaml
- v1alpha1_s3connection.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
